---
title: "EDA - Reddit Data about Soccer"
author:
  - name: Jingda Yang, Wendi Chu, Haiyu Xiao, Tingsong Li

execute:
  echo: false

format:
  html:
    embed-resources: true
    self-contained: true
    page-layout: full
    fig-cap-location: bottom
    toc: true
    toc-location: left
    toc-title: Contents
    #tbl-cap-location: bottom
---

## EDA Topics

- EDA

  1. 
  - Business Goal: Evaluate the relative popularity of teams and leagues by ranking the number of posts published between January 2023 and March 2023.
    
  - Technical Proposal: Develop a manual dictionary that associates major team and league names with their respective subreddit counterparts. Extract Reddit posts from a diverse set of subreddits listed in the dictionary. Subsequently, calculate the post count for each subreddit and visualize the findings using a bar plot.

   2. 
  - Business Goal: Determine which days of the week see the most activity from soccer fans, and whether this is driven by match days.
 
  - Technical Proposal: Get external soccer match schedule and data for the same time frame, filter and merge the Reddit activity data with the match schedule data based on the date. Count daily posts and comments in soccer subreddits, flag days with matches using the external database, and assess the relationship between match days and activity spikes. For visualization methods, illustrate the volume of posts/comments over time and compare average daily activity on match days versus non-match days.
  
  3. 
  - Business goal: Identify what aspects of soccer are most frequently discussed in different subreddits and what kind of topics are most likely to acquire high scores.

  - Technical proposal: Use NLP to identify the posts that mention different aspects of soccer, including tactics, league policies, transfers or fan culture. Then count the number of posts and calculate the average score of each aspect. Create several plots, like pie charts or bar plots, to visualize the count number and score of the most popular topics.


## 1. Basic Information Exploration

Filter Data Shape: 5617852 x 9.  
  
Filter Data Time Range:  
The minimum created_utc is: 2023-01-01 00:00:00  
The maximun created_utc is: 2023-03-31 23:59:59  

Filter Data Schema:  
 |-- author: string (nullable = true)  
 |-- author_flair_text: string (nullable = true)  
 |-- body: string (nullable = true)  
 |-- controversiality: long (nullable = true)  
 |-- created_utc: timestamp (nullable = true)  
 |-- gilded: long (nullable = true)  
 |-- score: long (nullable = true)  
 |-- stickied: boolean (nullable = true)  
 |-- subreddit: string (nullable = true)  

## 2. Find out the Most Popular Leagues and Clubs on Reddit 

```{python, echo=FALSE}
#| label: fig-polar
#| fig-cap: "Number of Comment for Each Soccer League"
from PIL import Image
with Image.open("../data/plots/count_comments_league.png") as img:
    display(img)
```

Figure 1 provided data reveals varying levels of activity across major soccer league subreddits. “PremierLeague” and “MLS” stand out as highly active communities, while “worldcup” also enjoys a substantial presence. In contrast, “seriea,” “Bundesliga,” and “LaLiga” have comparatively lower levels of engagement within their respective subreddits.

```{python, echo=FALSE}
#| label: fig-polar2
#| fig-cap: "Number of Rows for Each Subreddit"
with Image.open("../data/plots/count_comments_club.png") as img2:
    display(img2)
```

Figure 2, this barplot provides comment counts for popular European soccer clubs (three clubs for Premier League, La Liga, Serie A, and Bundesliga). The Premier League dominates, reflecting active discussions among English club enthusiasts. La Liga’s “Barca” enjoys a robust presence, while Serie A’s “ACMilan” showcases dedicated online discussions. Comparing with Premier League and La Liga, Serie A and Bundesliga are not popular on reddit but major clubs such as Milan and FC Bayern still stand out of the other clubs.

### Common Words of Comments on Soccer Subreddit
```{python, echo=FALSE}
#| label: fig-polar3
#| fig-cap: "Word Cloud - Common Words of Comments"
with Image.open("../data/plots/word_cloud.png") as img3:
    display(img3)
```

The soccer subreddit word cloud highlights key themes of discussions, such as strategic thinking ("think"), the excitement of the game ("game"), team dynamics ("team" and "club"), and fans' desires ("want"). Notably, the focus is more on the collective experience of soccer, with only a few specific club mentions like "Arsenal" rather than individual player names. The word "player" suggests a broader discussion of various players across different clubs. Overall, the word cloud reflects a community engaged in analyzing and sharing perspectives on soccer matches, strategies, and the overall team and club experience without emphasizing specific players.

## 3. Determine Which Days of the Week See the Most Activity from Soccer Fans, and Whether This is Driven by Match Days.
count_comments_everyday
```{python, echo=FALSE}
#| label: fig-polar4
#| fig-cap: "The Number of Comments Every Day"
with Image.open("../data/plots/count_comments_everyday.png") as img4:
    display(img4)
```

```{python, echo=FALSE}
#| label: tbl-planets5
#| tbl-cap: the classification report for test data(linear)
import pandas as pd
import numpy as np
df_schedule = pd.read_csv('../data/csv/football_schedule.csv')
# df_schedule = df.head(6)
df_schedule['date'] = pd.to_datetime(df_schedule['Date'])
df_schedule['date'] = df_schedule['date'].dt.strftime('%Y-%m-%d')
df_schedule['date'] = pd.to_datetime(df_schedule['date'])
df_schedule.drop('Date', axis=1, inplace=True)
cols = ['date'] + [col for col in df_schedule if col != 'date']
df_schedule = df_schedule[cols]
df_schedule['TotalMatches'] = df_schedule.iloc[:, 1:7].sum(axis=1)
df = df_schedule.head(6)
df
```

### Explore the relationship between the Daily Comments Counts and the Number of the Top League Matches Played

#### Line Plot

```{python, echo=FALSE}
#| label: fig-polar6
#| fig-cap: "Daily Number of Reddit Comments vs. Number of Matches"
with Image.open("../data/plots/daily_comments_matches.png") as img6:
    display(img6)
```

This line plot shows the pattern of the daily number of Reddit comments in the subreddits about soccer, and the daily number of soccer matches played in top leagues. There are similar traits in the two lines, for example on 2023-01-30 and 2023-01-31 there are few to none matches played, and the comments count on Reddit for these two days are also low; For every few days there are two days where around 20 matches are played, and on these days the number of Reddit comments also peaked. This time series line charts therefore show some degree of correlation between the number of comments and matches for each day.

#### Bar Plot

```{python, echo=FALSE} 
#| label: fig-polar7
#| fig-cap: "Daily Number of Reddit Comments vs. Number of Matches"
with Image.open("../data/plots/weekday_comments_matches.png") as img7:
    display(img7)
```

The bar chart explores the distribution of the number of Reddit comments and matches played on each weekday. First, on the weekends there are significantly more matches played, and much more comments made; However, even though the number of matches and comments are correlated on the weekends, there is little to none correlation between them on the weekdays. For example, on Mondays and Fridays, on average there are less than 50000 comments made, but there are still more than 3 matches played; But on Thursdays there are average more than 60000 comments made but almost no top leagues matches are played on Thursdays. Therefore, we can only conclude that the weekends are the time most matches are played and much more commands are made, but the more comments may be caused by users having more free time, other than more games being played.

## 4. Identify What Aspects of Soccer Are Most Frequently Discussed in Different Subreddits and What Kind of Topics Are Most Likely to Acquire High Scores.

For this problem, six different topics have been selected, which are commonly discussed in soccer forums:
  
- Soccer tactics 
- Transfers
- Player performances
- Player rankings
- Match analysis and previews
- Managerial decisions 
  
Each topic is associated with a series of relevant keywords. A search is conducted in the 'body' column to determine whether each post relates to a particular topic. Six dummy variables have been created to indicate whether each post contains information on these topics: 'soccer_tactics', 'transfers', 'player_performances', 'player_rankings', 'match_analysis_previews', 'managerial_decisions'.

Subsequently, calculations are performed to determine the total number, average score, and gild percentage of each topic. Finally, various visualizations are generated to present the data output.

```{python, echo=FALSE}
#| label: tbl-planets8
#| tbl-cap: Soccer Topic Summary Table
df2 = pd.read_csv('../data/csv/soccer_topic_summary.csv')
df2 = df2.head(6)
df2
```

#### Barplot: Number of Rows per Topic
```{python, echo=FALSE} 
#| label: fig-polar9
#| fig-cap: "Number of Rows per Topic"
with Image.open("../data/plots/soccer_topic_bar1.png") as img8:
    display(img8)
```

#### Pie chart: Proportion of Posts per Topic
```{python, echo=FALSE}
#| label: fig-polar10
#| fig-cap: "Proportion of Posts per Topic"
with Image.open("../data/plots/soccer_topic_pie.png") as img9:
    display(img9)
```

According to these two charts above, we can observe that Player Performances is the hottest topic in the Reddit posts related to soccer, while Match Analysis and Previews is discussed less frequently compared to other topics.

#### Barplot: Average Score per Topic
```{python, echo=FALSE}
#| label: fig-polar11
#| fig-cap: "Average Score per Topic"
with Image.open("../data/plots/soccer_topic_bar2.png") as img10:
    display(img10)
```

From this plot, we can conclude that the average score of posts related to Soccer Tactics is significantly lower than other topics, whereas the average scores of other five topics are quite similar. This suggests that users on Reddit are not so interested in the posts related to Soccer Tactics compared to other topics about soccer.

#### Barplot: Gild Percentage per Topic
```{python, echo=FALSE}
#| label: fig-polar12
#| fig-cap: "Gild Percentage per Topic"
with Image.open("../data/plots/soccer_topic_bar3.png") as img11:
    display(img11)
```

Unlike the average score distribution of each topic, the gild percentage of the topics show greater variety. Posts related to Player Performances or Match Analysis and Previews tend to have higher probabilities to be gilded. Also, it is interesting that although the number of posts about Match Analysis and Previews are smaller than other topics, the gild percentage of this topic is the highest among all.